version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true 
  pre_build:
    commands:
      - env
      - echo running tests file
      - $CODEBUILD_SRC_DIR_platform/scripts/run-unit-tests.sh 

  build:
    commands:
      - $CODEBUILD_SRC_DIR_platform/scripts/build-and-release-tag.sh

  post_build:
    commands:

